### ISSUE TITLE
报错还有正常走也报错

### ISSUE THREAD

**Issue by szzz666** [Vilatik/FalconAC-Rework#1]
日志文件
[server.log](https://github.com/Vilatik/FalconAC-Rework/files/11647612/server.log)
还有正常走也报错

**Comment by szzz666** [comment]
在哪里下载新版本
Where to download the new version

**Comment by Vilatik** [comment]
You can download new version from cloudburst or releases on github
Cloudburst: https://cloudburstmc.org/resources/falconac-rework.916/
Github Releases: https://github.com/Vilatik/FalconAC-Rework/releases/tag/FalconAC-1.0.1

**Comment by szzz666** [comment]
依旧报错
Still reporting an error

 [FATAL] Could not pass event 'cn.nukkit.event.server.DataPacketReceiveEvent' to 'FalconAC v1.3': null on me.liuli.falcon.listener.PacketListener
23:15:49 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:512) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2597) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:117) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1343) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1084) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:1052) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:769) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:82) [Nukkit-MOT-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "miscVL" because "cache" is null
        at me.liuli.falcon.manager.AnticheatManager.addVL(AnticheatManager.java:76) ~[?:?]
        at me.liuli.falcon.listener.PacketListener.onPacketReceive(PacketListener.java:70) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        ... 11 more

**Comment by Vilatik** [comment]
Seems like you using core with multiversion so plugin may not work properly on your core. I will try fix this issue, but for now try deleting your data folder in plugin folder

**Comment by szzz666** [comment]
Boss, which country are you from? Should I delete the old configuration file?

**Comment by Vilatik** [comment]
ye, you should try delete

**Comment by szzz666** [comment]
Deleting the old configuration file still reports an error.

**Comment by Vilatik** [comment]
I will try rewrite plugin for core you using but i dont give any guarantee that i can do it. Also, it will be very helpful if you give me link to core that you use.

**Comment by szzz666** [comment]
https://github.com/MemoriesOfTime/NukkitPetteriM1Edition

**Comment by Vilatik** [comment]
I will try my best, thanks for suppory!

**Comment by szzz666** [comment]
I should say thank you. Thank you for your trouble.
